import { WebhookPayload } from "../../types/inspection.types";

const GRADE_EMOJI: Record<string, string> = {
  S: "🏆",
  A: "✅",
  B: "🟢",
  C: "🟡",
  D: "🟠",
  F: "🔴",
};

/**
 * Format a WebhookPayload as a GitHub PR / Issue comment body.
 * The caller is responsible for POSTing to the GitHub API with the correct
 * Authorization header; this adapter just produces { body: "<markdown>" }.
 */
export function toGitHubPayload(payload: WebhookPayload): Record<string, unknown> {
  const { inspection, event, breaches } = payload;
  const { overall, grade } = inspection.scoreCard;
  const gradeEmoji = GRADE_EMOJI[grade] ?? "⚪";

  const lines: string[] = [
    `## ${gradeEmoji} ouroboros インスペクション結果`,
    "",
    "| 項目 | 値 |",
    "|---|---|",
    `| 総合スコア | **${overall}/100** (グレード: **${grade}**) |`,
    `| 言語 | \`${inspection.language}\` |`,
    `| 指摘件数 | ${inspection.findingCount}件 |`,
    `| 改善案 | ${inspection.recommendationCount}件 |`,
    "",
    "### サマリー",
    "",
    inspection.summary,
  ];

  if (event === "inspection.threshold_breached" && breaches && breaches.length > 0) {
    lines.push("", "### 閾値超過");
    for (const b of breaches) {
      lines.push(
        `- **${b.category}**: 設定閾値 ${b.threshold}点 → 実測値 **${b.actual}点**`
      );
    }
  }

  if (event === "inspection.failed" && payload.error) {
    lines.push("", "### エラー詳細", "", `\`\`\`\n${payload.error}\n\`\`\``);
  }

  if (inspection.url) {
    lines.push("", `[詳細レポートを見る](${inspection.url})`);
  }

  lines.push(
    "",
    "---",
    "*Generated by [ouroboros](https://github.com/nemonet1337/ouroboros) AI Inspection System*"
  );

  return { body: lines.join("\n") };
}
